//------------------------------------------------------------------------------------------------------
//
// This is a part of Seetron Engine
//
// Copyright (c) 2018 Nicolas Arques. All rights reserved.
//
//------------------------------------------------------------------------------------------------------

#pragma once

enum LXInternalShader
{
	LX_SHADER_BLIT,
	LX_SHADER_BLITDCNP,
	LX_SHADER_COLLECTHIGHLIGHT,
	LX_SHADER_COLORIZER,
	LX_SHADER_DOF_DECOMPOSE,
	LX_SHADER_DOF_X,
	LX_SHADER_DOF_Y,
	LX_SHADER_DRAWLAYERDEEPNESS,
	LX_SHADER_DRAWLAYERTRANSPARENCY,
	LX_SHADER_DRAWQUAD,
	LX_SHADER_DRAWQUADTEXTURED,
	LX_SHADER_DRAWQUADTEXTURED_ALPHA_TO_RGB,
	LX_SHADER_DRAWQUADTEXTURED_RGB_ONLY,
	LX_SHADER_DRAWSSAO_X,
	LX_SHADER_DRAWSSAO_Y,
	LX_SHADER_DRAWSSAO_X_MS,
	LX_SHADER_DRAWSSAO_Y_MS,
	LX_SHADER_DRAWTEXT,
	LX_SHADER_GAUSSIAN_X,
	LX_SHADER_GAUSSIAN_Y,
	LX_SHADER_HIGHLIGHTING,
	LX_SHADER_LIGHTING,
	LX_SHADER_FXAA,
	LX_SHADER_RENDERANCHOR,
	LX_SHADER_RENDERBACKGROUND,
	LX_SHADER_RENDERBACKGROUND_CUBE,
	LX_SHADER_RENDERLINE,
	LX_SHADER_RENDERLINES,
	LX_SHADER_RENDERNORMALS,
	LX_SHADER_RENDERSUN,
	LX_SHADER_SELECTION,
	LX_SHADER_SHADOW,
	LX_SHADER_SILHOUETTE,
	LX_SHADER_SSAO,
	LX_SHADER_SSAO_MS,
	LX_SHADER_TEST,
	LX_SHADER_TONEMAPPING
};
